name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        #run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        run: echo "version=${GITHUB_REF/refs\/tags\//}"  >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: carezkh
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: carezkh
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - id: echo_tag
        run: echo tag ${{ steps.get_version.outputs.version }}

      - id: build_test
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            carezkh/test:${{ steps.get_version.outputs.version }}
            ghcr.io/carezkh/test:${{ steps.get_version.outputs.version }}
