name: release-test

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}"  >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: caretest
          password: ${{ secrets.DOCKERHUB_CARETEST_PUSH_TOKEN }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: carezkh
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - id: echo_tag
        run: echo tag ${{ steps.get_version.outputs.version }}

      - id: pwd
        run: pwd

      - id: echo pwd
        run: echo ${{ steps.pwd.outputs }}

      - id: build_test
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            caretest/test:${{ steps.get_version.outputs.version }}
            ghcr.io/carezkh/test:${{ steps.get_version.outputs.version }}
